version: "3"

tasks:
  # ==========
  # Terraform
  # ==========

  plan-infra:
    dir: infra
    desc: Plan infra
    cmds:
      - terraform plan -var-file="../.tfvars"

  apply-infra:
    dir: infra
    desc: Apply infra
    cmds:
      - terraform apply -var-file="../.tfvars"

  # ==========
  # OCI
  # ==========

  get-ampere-images:
    desc: Get availble images for Ampere machines
    dir: infra
    cmds:
      - |
        COMPARTMENT_ID=$(terraform output -raw compartment_id)
        oci compute image list \
         --compartment-id $COMPARTMENT_ID \
         --operating-system "Oracle Linux" \
         --shape "VM.Standard.A1.Flex" \
         --output table

  generate-ephemeral-key:
    desc: Generate an ephemeral SSH keypair
    cmds:
      - |
        echo "🔑 Generating ephemeral SSH keypair..."
        mkdir -p .ssh
        ssh-keygen -t rsa -b 2048 -f .ssh/ephemeral -N "" -q
        echo "✅ Ephemeral SSH keypair generated at .ssh/ephemeral(.pub)"

  create-session:
    desc: Create a session with the bastion host for debugging
    dir: infra
    cmds:
      - |
        BASTION_ID=$(terraform output -raw bastion_id)
        RESOURCE_ID=$(terraform output -raw server_id)
        PRIVATE_IP=$(terraform output -raw server_ip)

        SESSION_ID=$(oci bastion session create-managed-ssh \
        --bastion-id $BASTION_ID \
        --target-resource-id $RESOURCE_ID \
        --target-private-ip $PRIVATE_IP \
        --ssh-public-key-file ../.ssh/ephemeral.pub \
        --display-name "k3s-debug" \
        --target-os-username opc \
        --session-ttl 10800 \
        --query 'data.id' --raw-output)

        echo $SESSION_ID

  connect-to-session:
    desc: Connect to a Bastion host session (polls until ready)
    cmds:
      - |
        SESSION_ID={{ .SESSION_ID }}
        echo "🔁 Waiting for session $SESSION_ID to become ACTIVE..."

        for i in {1..30}; do
          STATE=$(oci bastion session get --session-id "$SESSION_ID" --query 'data."lifecycle-state"' --raw-output)
          echo "⏳ Session state: $STATE"
          if [[ "$STATE" == "ACTIVE" ]]; then
            echo "✅ Session is ACTIVE!"
            break
          fi
          sleep 5
        done

        if [[ "$STATE" != "ACTIVE" ]]; then
          echo "❌ Timed out waiting for session to become ACTIVE."
          exit 1
        fi

        echo "🔐 Fetching SSH command..."
        SSH_CMD=$(oci bastion session get \
          --session-id "$SESSION_ID" \
          --query 'data."ssh-metadata".command' \
          --raw-output)

        SSH_CMD="${SSH_CMD//<privateKey>/.ssh/ephemeral}"

        echo "🚀 Connecting with command:"
        echo "$SSH_CMD"

        eval "$SSH_CMD"

  session:
    desc: Create a session and connect to it
    cmds:
      - |
        task generate-ephemeral-key
        SESSION_ID=$(task create-session)
        task connect-to-session SESSION_ID=$SESSION_ID

  # ==========
  # Kubectl
  # ==========

  merge-kube-config:
    desc: Get kubectl config and merge with existing file
    dir: infra
    cmds:
      - |
        VAULT_ID=$(terraform output -raw vault_id)

        if [[ -z "$VAULT_ID" ]]; then
          echo "❌ Failed to get Vault ID from Terraform."
          exit 1
        fi

        SECRET_B64=$(oci secrets secret-bundle get-secret-bundle-by-name \
          --secret-name kubeconfig \
          --vault-id "$VAULT_ID" \
          --query 'data."secret-bundle-content".content' \
          --raw-output)

        if [[ -z "$SECRET_B64" ]]; then
          echo "❌ Failed to retrieve kubeconfig secret."
          exit 1
        fi

        echo "$SECRET_B64" | base64 --decode > /tmp/kubeconfig.remote

        echo "Merging kubeconfig with existing ~/.kube/config..."
        export KUBECONFIG=/tmp/kubeconfig.remote:~/.kube/config
        kubectl config view --flatten > /tmp/kubeconfig.merged
        mkdir -p ~/.kube
        mv /tmp/kubeconfig.merged ~/.kube/config
        chmod 600 ~/.kube/config
        echo "✅ Kubeconfig merged successfully."

  # ==========
  # Helm & Kustomize
  # ==========

  upgrade-all:
    desc: Install or upgrade all Helm charts
    cmds:
      - task: upgrade-cilium
      - task: upgrade-envoy
      - task: upgrade-external-secrets
      - task: upgrade-identity
      - task: upgrade-cert-manager
      - task: upgrade-argocd
      - task: upgrade-kustomize
      - task: upgrade-temporal

  upgrade-identity:
    desc: Install or upgrade manifests for identity
    dir: helm/identity
    cmds:
      - kubectl apply -f ./manifests/binding.yaml
      - kubectl apply -f ./manifests/route.yaml
      - kubectl apply -f ./manifests/secrets.yaml
      - kubectl apply -f ./manifests/gar.yaml

  upgrade-cilium:
    desc: Install or upgrade Cilium Helm chart
    dir: helm/cilium
    cmds:
      # We must use v1.1.0 as apparently Envoy doesn't like the newer versions
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
      - helm upgrade --install -f values.yaml --namespace=kube-system cilium ./chart

  uninstall-cilium:
    desc: Uninstall Cilium Helm chart
    cmds:
      - helm uninstall cilium

  upgrade-envoy:
    desc: Install or upgrade Envoy Gateway Helm chart
    dir: helm/envoy
    cmds:
      - |
        helm upgrade --install eg oci://docker.io/envoyproxy/gateway-helm \
        --version v1.4.1 \
        -n envoy-gateway-system \
        --create-namespace \
        -f values.yaml
      - kubectl apply -f ./manifests/gateway.yaml

  uninstall-envoy:
    desc: Uninstall Envoy Gateway Helm chart
    cmds:
      - helm uninstall eg

  upgrade-external-secrets:
    desc: Install or upgrade External Secrets Helm chart
    dir: helm/external-secrets
    cmds:
      - kubectl apply -f ./crds/bundle.yaml
      - helm dependency build ./chart
      - helm upgrade --install -f values.yaml --create-namespace --namespace=external-secrets external-secrets ./chart
      - kubectl apply -f ./manifests/store.yaml

  uninstall-external-secrets:
    desc: Uninstall External Secrets Helm chart
    cmds:
      - helm uninstall external-secrets

  upgrade-cert-manager:
    desc: Install or upgrade Cert Manager Helm chart
    dir: helm/cert-manager
    cmds:
      - helm repo add jetstack https://charts.jetstack.io --force-update
      - helm upgrade --install -f values.yaml --create-namespace --namespace=cert-manager --version v1.17.2 cert-manager jetstack/cert-manager
      - kubectl apply -f ./manifests/secrets.yaml
      - kubectl apply -f ./manifests/issuer.yaml

  uninstall-cert-manager:
    desc: Uninstall Cert Manager Helm chart
    cmds:
      - helm uninstall cert-manager

  upgrade-argocd:
    desc: Install or upgrade ArgoCD Helm chart
    dir: helm/argocd
    cmds:
      - kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f ./manifests/secrets.yaml
      - helm repo add dandydeveloper https://dandydeveloper.github.io/charts/ --force-update
      - helm dependency build ./chart
      - helm upgrade --install -f values.yaml --create-namespace --namespace=argocd argocd ./chart
      - kubectl apply -f ./manifests/route.yaml
      - kubectl apply -f ./manifests/apps.yaml

  uninstall-argocd:
    desc: Uninstall ArgoCD Helm chart
    cmds:
      - helm uninstall argocd

  upgrade-temporal:
    desc: Install or upgrade Temporal Helm chart
    dir: helm/temporal
    cmds:
      - kubectl create namespace temporal --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f ./manifests/secrets.yaml
      - kubectl apply -f ./manifests/route.yaml
      - kubectl apply -f ./manifests/ca.yaml
      - kubectl apply -f ./manifests/certs.yaml
      - helm dependencies update ./chart
      - helm upgrade --install -f values.yaml --create-namespace --namespace=temporal temporal ./chart
      - kubectl delete job temporal-bootstrap-namespaces -n temporal --ignore-not-found
      - kubectl apply -f ./manifests/namespaces.yaml


  uninstall-temporal:
    desc: Uninstall Temporal Helm chart
    cmds:
      - helm uninstall temporal

  upgrade-kustomize:
    desc: Install or upgrade Kubernetes manifests via Kustomize
    dir: kustomize
    cmds:
      - kubectl apply -k .

  # ==========
  # Runtime
  # ==========

  hubble-ui:
    desc: Show observability for cluster
    cmds:
      - cilium hubble ui
