version: "3"

tasks:
  plan-infra:
    dir: infra
    desc: Plan infra
    cmds:
      - terraform plan -var-file="../.tfvars"

  apply-infra:
    dir: infra
    desc: Apply infra
    cmds:
      - terraform apply -var-file="../.tfvars"

  get-ampere-images:
    desc: Get availble images for Ampere machines
    requires:
      vars: [OCID]
    cmds:
      - oci compute image list --compartment-id {{.OCID}} --operating-system "Oracle Linux" --shape "VM.Standard.A1.Flex" --output table

  create-session:
    desc: Create a session with the bastion host for debugging
    requires:
      vars: [BASTION_ID, RESOURCE_ID, PRIVATE_IP]
    cmds:
      - oci bastion session create-managed-ssh --bastion-id {{ .BASTION_ID }} --target-resource-id {{ .RESOURCE_ID }} --target-private-ip {{ .PRIVATE_IP }} --ssh-public-key-file ~/.ssh/id_rsa.pub --display-name "k3s-debug" --target-os-username opc --session-ttl 10800

  install-cilium:
    desc: Install or upgrade Cilium Helm chart
    dir: helm/cilium
    cmds:
      - helm upgrade --install -f values.yaml cilium ./chart

  uninstall-cilium:
    desc: Install Cilium Helm chart
    cmds:
      - helm uninstall cilium
