version: "3"

tasks:
  # ==========
  # Terraform
  # ==========

  plan-infra:
    dir: infra
    desc: Plan infra
    cmds:
      - terraform plan -var-file="../.tfvars"

  apply-infra:
    dir: infra
    desc: Apply infra
    cmds:
      - terraform apply -var-file="../.tfvars"

  # ==========
  # OCI
  # ==========

  get-ampere-images:
    desc: Get availble images for Ampere machines
    requires:
      vars: [OCID]
    cmds:
      - oci compute image list --compartment-id {{.OCID}} --operating-system "Oracle Linux" --shape "VM.Standard.A1.Flex" --output table

  create-session:
    desc: Create a session with the bastion host for debugging
    requires:
      vars: [BASTION_ID, RESOURCE_ID, PRIVATE_IP]
    cmds:
      - oci bastion session create-managed-ssh --bastion-id {{ .BASTION_ID }} --target-resource-id {{ .RESOURCE_ID }} --target-private-ip {{ .PRIVATE_IP }} --ssh-public-key-file ~/.ssh/id_rsa.pub --display-name "k3s-debug" --target-os-username opc --session-ttl 10800

  # ==========
  # Helm
  # ==========

  upgrade-all:
    desc: Install or upgrade all Helm charts
    cmds:
      - task: upgrade-cilium
      - task: upgrade-cert-manager
      - task: upgrade-external-secrets

  upgrade-cilium:
    desc: Install or upgrade Cilium Helm chart
    dir: helm/cilium
    cmds:
      - helm upgrade --install -f values.yaml --namespace=kube-system cilium ./chart

  uninstall-cilium:
    desc: Install Cilium Helm chart
    cmds:
      - helm uninstall cilium

  upgrade-cert-manager:
    desc: Install or upgrade Cert Manager Helm chart
    dir: helm/cert-manager
    cmds:
      - helm repo add jetstack https://charts.jetstack.io --force-update
      - helm upgrade --install -f values.yaml --create-namespace --namespace=cert-manager --version v1.17.2 cert-manager jetstack/cert-manager

  uninstall-cert-manager:
    desc: Install Cert Manager Helm chart
    cmds:
      - helm uninstall cert-manager

  upgrade-external-secrets:
    desc: Install or upgrade External Secrets Helm chart
    dir: helm/external-secrets
    cmds:
      - kubectl apply -f ./crds/bundle.yaml
      - helm dependency build ./chart
      - helm upgrade --install -f values.yaml --create-namespace --namespace=external-secrets external-secrets ./chart

  uninstall-external-secrets:
    desc: Install External Secrets Helm chart
    cmds:
      - helm uninstall external-secrets

  # ==========
  # Runtime
  # ==========

  hubble-ui:
    desc: Show observability for cluster
    cmds:
      - cilium hubble ui
