apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxy-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: proxy-secrets
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: auth_client_secret
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: auth_cookie_secret
