apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: oci-secret-store
    kind: ClusterSecretStore
  target:
    name: github-client-secret
  data:
    - secretKey: value
      remoteRef:
        key: argocd_github_client_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: portfolio
  server: https://kubernetes.default.svc